### ISSUE TITLE
Use webhook to deploy to servers

### ISSUE THREAD

**Issue by ArtemSBulgakov** [one-zero-eight/InNoHassle-Server#6]
Instead of letting GitHub Actions to connect to SSH, we can set up webhooks (ex. https://github.com/adnanh/webhook) which will run a script to pull Docker images and run services.

**Comment by evermake** [comment]
What's wrong with SSH script?

**Comment by dantetemplar** [comment]
@evermake Microsoft knows too much about your server

**Comment by ArtemSBulgakov** [comment]
> What's wrong with SSH script?

It gives GitHub access to our servers. If something goes wrong (e.g. GitHub's security mechanisms allowed some modifications in workflows we use), our production servers may be compromised.
