### ISSUE TITLE
Change Swagger Favicon

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/InNoHassle-Server#7]
### Describe the feature

The favicon from fast api is currently being used at https://api.innohassle.ru/swagger/favicon.png. Therefore, the developer is confused between the fastapi documentation and the swagger itself.

### Suggested solution

Put our icon or Swagger icon at https://api.innohassle.ru/swagger/favicon.png

Swagger: https://static1.smartbear.co/swagger/media/assets/swagger_fav.png

**Comment by ArtemSBulgakov** [comment]
Please attach png in file as the URL is not accessible from Russia.

**Comment by ArtemSBulgakov** [comment]
Check out now at https://api.innohassle.ru/swagger/favicon.png.

It is already attached on https://api.innohassle.ru/events/staging-v0/docs. Other APIs will have the favicon after the solution for one-zero-eight/InNoHassle-Events#55 will be transferred to all repositories.
